export  const buttonData = [
    {button: "CE",
    id: "clear"},
    { button: "C",
    id: "backspace"},
    {button: "%",
    id: "modulus"},
    // { button: "÷",
    { button: "/",
    id: "divide"},
    { button: "8",
    id: "eight"} ,
    {button: "7",
    id: "seven"} ,
    {button: "9",
    id: "nine" },
    // { button: "x",
    {button: "*",
    id: "multiply"} ,
    {button: "4",
    id: "four"} ,
    {button: "5",
    id: "five" },
    {button: "6",
    id: "six"} ,
    {button: "-",
    id: "subtract"} ,
    {button: "1",
    id: "one" },
    {button: "2",
    id: "two" },
    {button: "3",
    id: "three"} ,
    {button: "+",
    id: "add"} ,
    {button: ".",
    id: "decimal"} ,
    {button: "0",
    id: "zero"} ,
    {button: "=",
    id: "equals"} ,
]

